logging:
  level:
    org:
      springframework:
        jdbc:
          core: trace

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/fast_sns?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    password:


springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/api-docs.html
  packagesToScan: junseok.snr.sns.controller
  pathsToMatch: /api
  showActuator: true
#  use-management-port: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: openapi, swagger-ui
